version: "3.9"

services:
  app:
    build: .
    container_name: agentic-api
    env_file:
      - .env
    environment:
      VECTOR_DB_URL: "http://qdrant:6333"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1
    volumes:
      - ./app:/app/app
      - ./data/docs:/data/docs
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - redis
      - jaeger

  redis:
    image: redis:7.2-alpine
    container_name: agentic-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:v1.11.0
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: agentic-jaeger
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # UI Port
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

volumes:
  redis_data:
